[{"raw":{},"required":["Filename","Size"],"package":"python3-pytest-instafail","source":"pytest-instafail","version":"0.5.0-1","section":"python","priority":"optional","architecture":"all","depends":["python3-pytest","python3:any"],"suggests":["python-pytest-instafail-doc"],"installedSize":33,"maintainer":"Debian QA Group <packages@qa.debian.org>","description":"plugin for py.test that shows failures and errors instantly","homepage":"https://github.com/pytest-dev/pytest-instafail","filename":"pool/main/p/pytest-instafail/python3-pytest-instafail_0.5.0-1_all.deb","size":9432,"md5":"b7f0c02df29aaf4344bdf9d77bca583c","sha256":"6caf9bb331e68c463defbd5a53153c5a03acb1e71848706be58ebb8d29634b66","descriptionMd5":"4acabc61b3293224ea4a27802dc75041"}]