[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-pyside6.qtnetworkauth",
	"source": "pyside6",
	"version": "6.8.2.1-2",
	"section": "python",
	"priority": "optional",
	"architecture": "amd64",
	"depends": [
		"python3-pyside6.qtcore",
		"python3-pyside6.qtnetwork",
		"python3 (>= 3~)",
		"libc6 (>= 2.4)",
		"libpyside6-py3-6.8 (>= 6.8.2.1)",
		"libqt6core6t64 (>= 6.8.2)",
		"libqt6network6 (>= 6.8)",
		"libqt6networkauth6 (>= 6.8.2)",
		"libshiboken6-py3-6.8 (>= 6.8.2.1)",
		"libstdc++6 (>= 5)"
	],
	"installedSize": 372,
	"maintainer": "Debian Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>",
	"description": "Python bindings for Qt 6 NetworkAuth (Python 3)",
	"homepage": "https://wiki.qt.io/Qt_for_Python",
	"filename": "pool/main/p/pyside6/python3-pyside6.qtnetworkauth_6.8.2.1-2_amd64.deb",
	"size": 89984,
	"md5": "0d0a3c8e37489212d8a1a22836862bf8",
	"sha256": "926bc5e05411a21b73fd9fc9aeee84e814cc342dc7830c08527c651d4dc0fb7b",
	"descriptionMd5": "e70eb24db824d791066d2d1b9d3f171d"
}]