[{"raw":{},"required":["Filename","Size"],"package":"python3-pytest-rerunfailures","source":"pytest-rerunfailures","version":"14.0-2","section":"python","priority":"optional","architecture":"all","depends":["python3-packaging","python3-pytest","python3:any"],"installedSize":61,"maintainer":"Debian Python Team <team+python@tracker.debian.org>","description":"pytest plugin to re-run tests to eliminate flaky failures","homepage":"https://github.com/pytest-dev/pytest-rerunfailures","filename":"pool/main/p/pytest-rerunfailures/python3-pytest-rerunfailures_14.0-2_all.deb","size":16500,"md5":"bc9076ae804d074198e5f86a8cf3ada0","sha256":"9a7a90d7acd3b1cff0c5ca6892ee72651ef3a1cd8db2a92a797425b55ff741ca","descriptionMd5":"b39ddd4149884d1e62c3622245de3f54"}]