[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-bleak-retry-connector",
	"source": "bleak-retry-connector",
	"version": "3.10.0-1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-async-timeout | python3-supported-min (>= 3.11)",
		"python3-dbus-fast",
		"python3:any"
	],
	"installedSize": 85,
	"maintainer": "Debian Python Team <team+python@tracker.debian.org>",
	"description": "Connector for Bleak Clients that handles transient connection failures",
	"homepage": "https://github.com/bluetooth-devices/bleak-retry-connector",
	"filename": "pool/main/b/bleak-retry-connector/python3-bleak-retry-connector_3.10.0-1_all.deb",
	"size": 26036,
	"md5": "41ec40ce40e1c117ae368a9a6e198e6b",
	"sha256": "08df10b3cd425abd73fa9bc59109a8a03904c036510467684810f03585aaf3b2",
	"descriptionMd5": "94cf3179d80dc95dc44c0b30cf94cbad"
}]