[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "bareos-filedaemon-python-plugin",
	"source": "bareos",
	"version": "16.2.6-5",
	"section": "python",
	"priority": "optional",
	"architecture": "amd64",
	"depends": [
		"bareos-common (= 16.2.6-5)",
		"libc6 (>= 2.14)",
		"libcap2 (>= 1:2.10)",
		"libgcc1 (>= 1:3.0)",
		"libgnutls30 (>= 3.6.5)",
		"libjansson4 (>= 2.0.1)",
		"liblzo2-2",
		"libpython2.7 (>= 2.7)",
		"libstdc++6 (>= 4.1.1)",
		"libwrap0 (>= 7.6-4~)",
		"zlib1g (>= 1:1.1.4)"
	],
	"preDepends": [
		"debconf (>= 1.4.30) | debconf-2.0"
	],
	"installedSize": 185,
	"maintainer": "Bareos Packaging Team <team+bareos@tracker.debian.org>",
	"description": "Backup Archiving Recovery Open Sourced - file daemon Python plugin",
	"homepage": "http://www.bareos.org/",
	"filename": "pool/main/b/bareos/bareos-filedaemon-python-plugin_16.2.6-5_amd64.deb",
	"size": 44944,
	"md5": "b093370282c84b372060bbad8fccf208",
	"sha256": "b1ae5a96ea32e00d44610054660a9981526d99574815b1ca57c6771176a1fc49",
	"descriptionMd5": "907d0721b418a31e846f1110bcccd809"
}]