[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-requestsexceptions",
	"source": "python-requestsexceptions",
	"version": "1.4.0-1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-pbr (>= 2.0.0)",
		"python3-urllib3 (>= 1.13)",
		"python3:any"
	],
	"installedSize": 23,
	"maintainer": "Debian OpenStack <team+openstack@tracker.debian.org>",
	"description": "import exceptions from bundled packages in requests. - Python 3.x",
	"homepage": "http://www.openstack.org/",
	"filename": "pool/main/p/python-requestsexceptions/python3-requestsexceptions_1.4.0-1_all.deb",
	"size": 4140,
	"md5": "9fe7db9474e6cac2f891beb43d693d31",
	"sha256": "724a312468ec4d0a4f844de7f32310c2fc923b7e51249aa45bc797da88ed944d",
	"descriptionMd5": "69eb6ceafcc256efdfb4eb0d4dce11c3"
}]