{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-pytest-rerunfailures",
	"source": "pytest-rerunfailures",
	"version": "9.1.1-1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-pkg-resources",
		"python3-pytest (>= 5.0)",
		"python3:any"
	],
	"installedSize": 46,
	"maintainer": "Debian Python Team <team+python@tracker.debian.org>",
	"description": "pytest plugin to re-run tests to eliminate flaky failures",
	"homepage": "https://github.com/pytest-dev/pytest-rerunfailures",
	"filename": "pool/main/p/pytest-rerunfailures/python3-pytest-rerunfailures_9.1.1-1_all.deb",
	"size": 11020,
	"md5": "bc8735097a9d73517a1b46873a3f6f02",
	"sha256": "feacb2d2438e0ee75e557e2c2cace5bf28ab61bd000ade99f14d4d97d928d676",
	"descriptionMd5": "b39ddd4149884d1e62c3622245de3f54"
}