{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-pytest-rerunfailures",
	"source": "pytest-rerunfailures",
	"version": "15.1-1",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-packaging",
		"python3-pytest",
		"python3:any"
	],
	"installedSize": 63,
	"maintainer": "Debian Python Team <team+python@tracker.debian.org>",
	"description": "pytest plugin to re-run tests to eliminate flaky failures",
	"homepage": "https://github.com/pytest-dev/pytest-rerunfailures",
	"filename": "pool/main/p/pytest-rerunfailures/python3-pytest-rerunfailures_15.1-1_all.deb",
	"size": 17180,
	"md5": "1738c11bfa1b78cb05d3de657bfe8568",
	"sha256": "052888dda62f9249a3f17dfbc3d6836352931abf6159d39ec95f4c736b5f4c73",
	"descriptionMd5": "b39ddd4149884d1e62c3622245de3f54"
}