[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-requestsexceptions",
	"source": "python-requestsexceptions",
	"version": "1.4.0-3",
	"section": "python",
	"priority": "optional",
	"architecture": "all",
	"depends": [
		"python3-pbr",
		"python3-urllib3",
		"python3:any"
	],
	"installedSize": 23,
	"maintainer": "Debian OpenStack <team+openstack@tracker.debian.org>",
	"description": "import exceptions from bundled packages in requests. - Python 3.x",
	"homepage": "http://www.openstack.org/",
	"filename": "pool/main/p/python-requestsexceptions/python3-requestsexceptions_1.4.0-3_all.deb",
	"size": 4188,
	"md5": "d21a5b4a7fd9830163f075d970fac571",
	"sha256": "89e176fda727eb7d22e036dea1b0cf0eaa77519454f915b17875e6e2da064b47",
	"descriptionMd5": "69eb6ceafcc256efdfb4eb0d4dce11c3"
}]