{"raw":{},"required":["Filename","Size"],"package":"python3-exceptiongroup","source":"python-exceptiongroup","version":"1.2.1-1","section":"python","priority":"optional","architecture":"all","depends":["python3:any"],"breaks":["python3-trio (<< 0.22)"],"installedSize":74,"maintainer":"Debian Python Team <team+python@tracker.debian.org>","description":"Backport of PEP 654 (exception groups)","homepage":"https://github.com/agronholm/exceptiongroup/","filename":"pool/main/p/python-exceptiongroup/python3-exceptiongroup_1.2.1-1_all.deb","size":19636,"md5":"f31754f98e1adc873a012f192d837dd0","sha256":"aabc86f5bf0a7b84fd57622e773cd12f0860cb1792b8b0eed1ca0989ffa9e4fb","descriptionMd5":"c0b3bacd074a82b7b90b912e5c5135a1"}