[{
	"raw": {},
	"required": [
		"Filename",
		"Size"
	],
	"package": "python3-pyside6.qtnetworkauth",
	"source": "pyside6 (6.8.2.1-4)",
	"version": "6.8.2.1-4+b1",
	"section": "python",
	"priority": "optional",
	"architecture": "amd64",
	"depends": [
		"python3-pyside6.qtcore",
		"python3-pyside6.qtnetwork",
		"python3 (>= 3~)",
		"libc6 (>= 2.4)",
		"libpyside6-py3-6.8 (>= 6.8.2.1)",
		"libqt6core6t64 (>= 6.8.2)",
		"libqt6network6 (>= 6.8)",
		"libqt6networkauth6 (>= 6.8.2)",
		"libshiboken6-py3-6.8 (>= 6.8.2.1)",
		"libstdc++6 (>= 5)"
	],
	"installedSize": 373,
	"maintainer": "Debian Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>",
	"description": "Python bindings for Qt 6 NetworkAuth (Python 3)",
	"homepage": "https://wiki.qt.io/Qt_for_Python",
	"filename": "pool/main/p/pyside6/python3-pyside6.qtnetworkauth_6.8.2.1-4+b1_amd64.deb",
	"size": 89972,
	"md5": "3123df39b9be2941e20a2981eb6c03f6",
	"sha256": "017035a63a92040454ad942e03ff7a632d5a12b78a4361a4b879ed85e858cbff",
	"descriptionMd5": "e70eb24db824d791066d2d1b9d3f171d"
}]